apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongodb-app
          image: 418272789147.dkr.ecr.us-east-1.amazonaws.com/ableasdale_mongodb_app:latest
          ports:
            - containerPort: 9992
          resources:
            requests:
              cpu: 1000m
              memory: 1512Mi
            limits:
              cpu: 1000m
              memory: 3068Mi
