apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb_app
  template:
    metadata:
      labels:
        app: mongodb_app
    spec:
      containers:
        - name: mongodb_app
          image: 418272789147.dkr.ecr.us-east-1.amazonaws.com/ableasdale_mongodb_app:latest
          ports:
            - containerPort: 9992
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
            limits:
              cpu: 100m
              memory: 2048Mi
