apiVersion: v1
kind: Service
metadata:
  name: mongodb-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mongodb-app
  ports:
    - protocol: TCP
      port: 9992
      targetPort: 9992